### ISSUE TITLE
Error trying to add this extension to Chrome - Multiple users affected

### ISSUE THREAD

**Issue by thejamabides** [clupasq/ChromeHttpRequestBlocker#14]
Package is invalid. Details: 'Could not load icon 'images/icon16.png' specified in 'icons'.'.

Any help would be appreciated... Was able to install on Friday, and today this is happening for everyone that I can find that is trying to install.

**Comment by clupasq** [comment]
I'm sorry for the inconvenience; it was an error on my side.
I have now fixed the error and submitted an updated package.

Hopefully it'll be reviewed quickly.

**Comment by clupasq** [comment]
The new version to look for is 1.0.6.

**Comment by thejamabides** [comment]
Thank you!

**Comment by clupasq** [comment]
You're welcome! :smile: 
I just checked and the new version is online and it works again.
