### ISSUE TITLE
Migrate to Manifest V3

### ISSUE THREAD

**Issue by geoffbon** [clupasq/ChromeHttpRequestBlocker#18]
It looks like Chrome will kill this extension soon with the manifest V3 requirement.  Can we please get the extension updated to support this?

**Comment by clupasq** [comment]
I have implemented Manifest v3 and submitted the extension for review.

The UI has changed significantly (I've simplified it), but the rules you have defined will show up in the new Options screen.

**Comment by clupasq** [comment]
The manifest v3 version is available. 🎉
