### ISSUE TITLE
Used this for years but has stopped working

### ISSUE THREAD

**Issue by a2d** [clupasq/ChromeHttpRequestBlocker#9]
Great plugin and simple to use, but hasn't worked for a couple of months now. 
Verified by installing another blocker which works but is not so straightforward to use

**Comment by clupasq** [comment]
Thanks for using this extension! I'm glad you like it.

I just checked and it does block requests. Can you please give an example of pattern that does not work?

**Comment by clupasq** [comment]
Closing this, as it's rather old.
@a2d, if you come up with examples that don't work, feel free to reopen.
